# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/FEB_pinout.xdc

# XDC: new/BD_constraints.xdc

# IP: ip/DDR_ila_0/DDR_ila_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DDR_ila_0 || ORIG_REF_NAME==DDR_ila_0} -quiet] -quiet
