# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/BD_constraints.xdc

# Block Designs: bd/Test_DDR/Test_DDR.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Test_DDR || ORIG_REF_NAME==Test_DDR} -quiet] -quiet

# IP: bd/Test_DDR/ip/Test_DDR_mig_7series_0_0/Test_DDR_mig_7series_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Test_DDR_mig_7series_0_0 || ORIG_REF_NAME==Test_DDR_mig_7series_0_0} -quiet] -quiet

# IP: bd/Test_DDR/ip/Test_DDR_microblaze_0_1/Test_DDR_microblaze_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Test_DDR_microblaze_0_1 || ORIG_REF_NAME==Test_DDR_microblaze_0_1} -quiet] -quiet

# IP: bd/Test_DDR/ip/Test_DDR_dlmb_v10_1/Test_DDR_dlmb_v10_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Test_DDR_dlmb_v10_1 || ORIG_REF_NAME==Test_DDR_dlmb_v10_1} -quiet] -quiet

# IP: bd/Test_DDR/ip/Test_DDR_ilmb_v10_1/Test_DDR_ilmb_v10_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Test_DDR_ilmb_v10_1 || ORIG_REF_NAME==Test_DDR_ilmb_v10_1} -quiet] -quiet

# IP: bd/Test_DDR/ip/Test_DDR_dlmb_bram_if_cntlr_1/Test_DDR_dlmb_bram_if_cntlr_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Test_DDR_dlmb_bram_if_cntlr_1 || ORIG_REF_NAME==Test_DDR_dlmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/Test_DDR/ip/Test_DDR_ilmb_bram_if_cntlr_1/Test_DDR_ilmb_bram_if_cntlr_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Test_DDR_ilmb_bram_if_cntlr_1 || ORIG_REF_NAME==Test_DDR_ilmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/Test_DDR/ip/Test_DDR_lmb_bram_1/Test_DDR_lmb_bram_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Test_DDR_lmb_bram_1 || ORIG_REF_NAME==Test_DDR_lmb_bram_1} -quiet] -quiet

# IP: bd/Test_DDR/ip/Test_DDR_mdm_1_1/Test_DDR_mdm_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Test_DDR_mdm_1_1 || ORIG_REF_NAME==Test_DDR_mdm_1_1} -quiet] -quiet

# IP: bd/Test_DDR/ip/Test_DDR_clk_wiz_1_0/Test_DDR_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Test_DDR_clk_wiz_1_0 || ORIG_REF_NAME==Test_DDR_clk_wiz_1_0} -quiet] -quiet

# IP: bd/Test_DDR/ip/Test_DDR_rst_clk_wiz_1_100M_0/Test_DDR_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Test_DDR_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==Test_DDR_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/Test_DDR/ip/Test_DDR_axi_smc_1/Test_DDR_axi_smc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Test_DDR_axi_smc_1 || ORIG_REF_NAME==Test_DDR_axi_smc_1} -quiet] -quiet

# IP: bd/Test_DDR/ip/Test_DDR_rst_mig_7series_0_81M_1/Test_DDR_rst_mig_7series_0_81M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Test_DDR_rst_mig_7series_0_81M_1 || ORIG_REF_NAME==Test_DDR_rst_mig_7series_0_81M_1} -quiet] -quiet

# XDC: c:/v23.1/FEB_test/FEB_test.gen/sources_1/bd/Test_DDR/Test_DDR_ooc.xdc
