# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/v23.1/FEB_test/FEB_test.srcs/sources_1/ip/AFE_DataPath_ila0/AFE_DataPath_ila0.xci
# IP: The module: 'AFE_DataPath_ila0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/v23.1/FEB_test/FEB_test.gen/sources_1/ip/AFE_DataPath_ila0/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'AFE_DataPath_ila0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/v23.1/FEB_test/FEB_test.gen/sources_1/ip/AFE_DataPath_ila0/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'AFE_DataPath_ila0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/v23.1/FEB_test/FEB_test.gen/sources_1/ip/AFE_DataPath_ila0/AFE_DataPath_ila0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'AFE_DataPath_ila0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/v23.1/FEB_test/FEB_test.srcs/sources_1/ip/AFE_DataPath_ila0/AFE_DataPath_ila0.xci
# IP: The module: 'AFE_DataPath_ila0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/v23.1/FEB_test/FEB_test.gen/sources_1/ip/AFE_DataPath_ila0/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'AFE_DataPath_ila0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/v23.1/FEB_test/FEB_test.gen/sources_1/ip/AFE_DataPath_ila0/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'AFE_DataPath_ila0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/v23.1/FEB_test/FEB_test.gen/sources_1/ip/AFE_DataPath_ila0/AFE_DataPath_ila0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'AFE_DataPath_ila0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
