# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/v23.1/FEB_test/FEB_test.srcs/sources_1/ip/PLL_AFE/PLL_AFE.xci
# IP: The module: 'PLL_AFE' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/v23.1/FEB_test/FEB_test.gen/sources_1/ip/PLL_AFE/PLL_AFE_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLL_AFE'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/v23.1/FEB_test/FEB_test.gen/sources_1/ip/PLL_AFE/PLL_AFE.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLL_AFE'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/v23.1/FEB_test/FEB_test.gen/sources_1/ip/PLL_AFE/PLL_AFE_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLL_AFE'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/v23.1/FEB_test/FEB_test.srcs/sources_1/ip/PLL_AFE/PLL_AFE.xci
# IP: The module: 'PLL_AFE' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/v23.1/FEB_test/FEB_test.gen/sources_1/ip/PLL_AFE/PLL_AFE_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLL_AFE'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/v23.1/FEB_test/FEB_test.gen/sources_1/ip/PLL_AFE/PLL_AFE.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLL_AFE'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/v23.1/FEB_test/FEB_test.gen/sources_1/ip/PLL_AFE/PLL_AFE_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLL_AFE'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
