set_property PACKAGE_PIN P15 [get_ports BD_VXO_P]
set_property IOSTANDARD MINI_LVDS_25 [get_ports BD_VXO_P]
set_property IOSTANDARD MINI_LVDS_25 [get_ports BD_VXO_N]

set_property PACKAGE_PIN N15 [get_ports BD_CpldRst]
set_property IOSTANDARD LVCMOS25 [get_ports BD_CpldRst]

# set_property PACKAGE_PIN U17 [get_ports {DBG[0]}]
# set_property PACKAGE_PIN N18 [get_ports {DBG[1]}]
# set_property PACKAGE_PIN U18 [get_ports {DBG[2]}]
# set_property PACKAGE_PIN T17 [get_ports {DBG[3]}]
# set_property PACKAGE_PIN R18 [get_ports {DBG[4]}]
# set_property PACKAGE_PIN N17 [get_ports {DBG[5]}]
# set_property PACKAGE_PIN T8 [get_ports {DBG[6]}]
# set_property PACKAGE_PIN T7 [get_ports {DBG[7]}]
# set_property PACKAGE_PIN T6 [get_ports {DBG[8]}]
# set_property PACKAGE_PIN V5 [get_ports {DBG[9]}]
# set_property IOSTANDARD LVCMOS25 [get_ports {DBG[9]}]
# set_property IOSTANDARD LVCMOS25 [get_ports {DBG[8]}]
# set_property IOSTANDARD LVCMOS25 [get_ports {DBG[7]}]
# set_property IOSTANDARD LVCMOS25 [get_ports {DBG[6]}]
# set_property IOSTANDARD LVCMOS25 [get_ports {DBG[5]}]
# set_property IOSTANDARD LVCMOS25 [get_ports {DBG[4]}]
# set_property IOSTANDARD LVCMOS25 [get_ports {DBG[3]}]
# set_property IOSTANDARD LVCMOS25 [get_ports {DBG[2]}]
# set_property IOSTANDARD LVCMOS25 [get_ports {DBG[1]}]
# set_property IOSTANDARD LVCMOS25 [get_ports {DBG[0]}]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets SysClk]

set_property IOSTANDARD LVCMOS25 [get_ports uart_rtl_0_rxd]
set_property IOSTANDARD LVCMOS25 [get_ports uart_rtl_0_txd]
set_property PACKAGE_PIN U17 [get_ports uart_rtl_0_rxd]
set_property PACKAGE_PIN N18 [get_ports uart_rtl_0_txd]

