# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/v23.1/FEB_test/FEB_test.srcs/sources_1/ip/PLL_0/PLL_0.xci
# IP: The module: 'PLL_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/v23.1/FEB_test/FEB_test.gen/sources_1/ip/PLL_0/PLL_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLL_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/v23.1/FEB_test/FEB_test.gen/sources_1/ip/PLL_0/PLL_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLL_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/v23.1/FEB_test/FEB_test.gen/sources_1/ip/PLL_0/PLL_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLL_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/v23.1/FEB_test/FEB_test.srcs/sources_1/ip/PLL_0/PLL_0.xci
# IP: The module: 'PLL_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/v23.1/FEB_test/FEB_test.gen/sources_1/ip/PLL_0/PLL_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLL_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/v23.1/FEB_test/FEB_test.gen/sources_1/ip/PLL_0/PLL_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLL_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/v23.1/FEB_test/FEB_test.gen/sources_1/ip/PLL_0/PLL_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLL_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
